### ISSUE TITLE
Typo on line 1

### ISSUE THREAD

**Issue by ghost** [KararTY/copypasta#1]
The Github isnt just a place; **it's** a version control system where we push our commits in a PR to upstream and enjoy watching the paj ladder squash merge.

Okayge TeaTime

**Comment by KararTY** [comment]
![pajaAAAAAAAAAAA](https://user-images.githubusercontent.com/13697809/114277778-f1267500-9a2c-11eb-8537-8962951071da.gif)
Make it a PR.
